from tiktok_1 import HU, RF, FI, SN, DP, AU
TT = [
# ---------------- SEMANA 3 ----------------
("24/10","10h","Série · Coisas que só... (pt. 6)","Vídeo","13 s",
 "coisas que só quem trabalha em escritório contábil entende (parte 6)",
 "1) Ana abre o e-mail: 'Assunto: URGENTE' com 'oi tudo bem' no corpo e nenhum anexo. 2) Júlia procurando o token A3 do cliente na gaveta, acha 3 iguais sem etiqueta. 3) Pedro (estagiário) pergunta 'é pra lançar ou pra conferir?' e todos respondem 'conferir'.",
 "parte 6 🫠 qual você vive toda semana?", HU, "Som em alta CML", "G"),
("24/10","15h","Ferramentas que eu indicaria #3","Carrossel de fotos","6 fotos",
 "o que eu colocaria num escritório contábil novo (com orçamento pequeno)",
 "1) capa; 2) 2 monitores por pessoa (o maior upgrade barato); 3) headset decente; 4) certificados A1 organizados com controle de vencimento; 5) uma rotina de backup; 6) automação no que é repetitivo, tipo baixar XML.",
 "o 2 muda a vida, pode confiar 🖥️🖥️", AU, "Som leve CML", "D"),
("24/10","20h","Trend #2","Vídeo","8 s",
 "a cara que eu faço quando o cliente diz que 'o contador anterior fazia de graça'",
 "Close na Júlia, olhar lento para a câmera, um gole de café.",
 "e nem fazia 🙂", HU, "Som trend CML de 'olhar lento'", "G"),
("25/10","10h","Departamento pessoal #1","Vídeo","30 s",
 "13º salário: 1ª parcela até 30 de novembro (avisa o cliente agora)",
 "Pedro (DP) na mesa com a folha aberta: 'A primeira parcela do 13º vai até 30 de novembro. Se o cliente deixa pra última semana, o caixa aperta junto com o DAS de dezembro. Avisar em outubro é o melhor favor que você faz.'",
 "copia o aviso e manda pros clientes hoje 📲", DP, "Lo-fi CML 5%", "G"),
("25/10","15h","Tipos de cliente #5","Vídeo","10 s",
 "tipos de cliente: o que manda a nota certa, no dia certo, com tudo organizado",
 "Júlia abre o e-mail, lê, fica parada, chama a Ana. As duas olham a tela em silêncio. Ana: 'emoldura'.",
 "esse cliente merece desconto 🥹", HU, "Som emocionante CML", "G"),
("25/10","20h","Bastidores do robô #4","Vídeo","10 s",
 "domingo, 00h: o que acontece no servidor enquanto o escritório dorme",
 "Gravação de tela com relógio 00:00, lista de clientes sincronizando um por um (fictícios), check verde em cada linha.",
 "domingo também tem nota 🌙", AU, "Som ambiente/eletrônico CML", "T"),
("26/10","07h30","Reforma em 30 segundos #6","Vídeo","35 s",
 "o XML mudou: onde ficam IBS e CBS (mostrando a tag)",
 "Gravação de tela com zoom no XML de exemplo, Ana narra: 'Dentro de cada item, o grupo IBSCBS: CST, cClassTrib, base, alíquota e valor de cada um. Se o seu sistema não lê esse grupo, o relatório do mês fica incompleto.'",
 "quem confere XML na mão vai precisar disso 🔎", RF, "Lo-fi CML 5%", "T + G"),
("26/10","12h15","Cliente diz vs contador entende #3","Vídeo","12 s",
 "cliente diz vs contador entende (edição abertura de empresa)",
 "'já abri a empresa' → 'abriu o MEI no CPF errado'; 'é só comércio' → 'tem serviço também'; 'não tenho funcionário' → 'tem o primo que ajuda'.",
 "abrir empresa é fácil, explicar depois que é difícil 😅", HU, "Som em alta CML", "G"),
("26/10","19h30","Um dia no escritório #4","Vídeo","40 s",
 "o que faz uma assistente fiscal (de verdade)",
 "Júlia narra enquanto mostra: conferir notas de entrada e saída, olhar canceladas, gerar relatório do mês, responder cliente, ajustar cadastro. 'Não é só lançar nota. É achar o que está errado antes de virar problema.'",
 "salva se você quer trabalhar com fiscal 📌", FI, "Lo-fi CML 10%", "G + T"),
("27/10","07h30","Glossário relâmpago #4","Vídeo","20 s",
 "notas emitidas vs destinadas (e por que as destinadas somem)",
 "Júlia: 'Emitidas são as notas que o cliente fez. Destinadas são as que fizeram contra o CNPJ dele, as compras. Se você só pede as emitidas, as compras ficam de fora e o crédito também.'",
 "as destinadas existem, eu juro 😅", FI, "Lo-fi CML", "G"),
("27/10","12h15","POV #4","Vídeo","9 s",
 "POV: o portal da prefeitura voltou depois de 3 horas",
 "Júlia clica em 'entrar', a página carrega, ela levanta os braços em silêncio, colega aplaude baixinho.",
 "as pequenas vitórias 🏆", HU, "Som de vitória CML", "G"),
("27/10","19h30","Opinião / debate #2","Vídeo","20 s",
 "escritório contábil precisa estar no TikTok?",
 "Ana: 'Meu cliente de 25 anos me achou aqui. O de 55 me achou por indicação. Os dois existem. Não é sobre dancinha, é sobre ser encontrado.'",
 "concorda ou acha perda de tempo? 👇", AU, "Sem música", "G"),
("28/10","07h30","Departamento pessoal #2","Vídeo","25 s",
 "o erro de eSocial que mais aparece no fim do mês",
 "Pedro: 'Admissão enviada depois do início do trabalho. O funcionário começou dia 1 e o cliente avisou dia 10. Dica: combina com o cliente que admissão chega antes do primeiro dia, por escrito.'",
 "manda pro cliente que contrata sem avisar 📲", DP, "Lo-fi CML", "G"),
("28/10","12h15","Série · Coisas que só... (pt. 7)","Vídeo","12 s",
 "coisas que só quem trabalha em escritório contábil entende (parte 7)",
 "1) O silêncio da sala quando alguém fala 'a Receita mudou o layout'. 2) Todo mundo olhando o mesmo monitor para ver um erro estranho. 3) Alguém diz 'achei!' e a sala inteira solta o ar.",
 "parte 7, a 3 é trabalho em equipe raiz 💚", HU, "Som em alta CML", "G"),
("28/10","19h30","Respondendo comentários #3","Vídeo","25 s",
 "respondendo: 'quanto tempo leva pra começar a usar um sistema assim?'",
 "Marcos: 'O que leva tempo é cadastrar os certificados dos clientes. Depois disso o robô começa a baixar sozinho. O resto é o time se acostumar a abrir o painel em vez do portal.'",
 "dúvida sobre automação? deixa aqui 👇", AU, "Sem música", "G"),
("29/10","07h30","Reforma em 30 segundos #7","Vídeo","35 s",
 "Split payment: o que é (e por que ainda não muda nada hoje)",
 "Ana: 'Split payment é quando o imposto é separado no momento do pagamento, direto pro governo. Está previsto na reforma, mas não está valendo agora. Hoje, foca no que já mudou: a nota e o XML.'",
 "notícia boa: dá tempo de aprender 😮‍💨", RF, "Lo-fi CML 5%", "G"),
("29/10","12h15","Tipos de cliente #6","Vídeo","10 s",
 "tipos de cliente: o que corrige o contador com vídeo do YouTube",
 "Celular mostra mensagem 'vi num vídeo que não preciso pagar isso'. Júlia e Ana se olham, Ana começa a digitar 'vamos marcar 15 minutos?'.",
 "a gente ama cliente curioso, mas 15 minutos de call resolvem 😅", HU, "Som em alta CML", "G"),
("29/10","19h30","Bastidores do robô #5","Vídeo","15 s",
 "fechamento do mês: de 3 dias para 1 tarde",
 "Antes (texto): portal por portal, planilha. Depois: Júlia gera relatório do mês em PDF e Excel no painel, baixa o ZIP do mês. Sem exagero de efeito.",
 "o fechamento não precisa ser maratona 🏁", AU, "Lo-fi CML", "T + G"),
("30/10","07h30","Prazo da semana","Vídeo","15 s",
 "último dia útil do mês: o que conferir hoje",
 "Júlia no quadro: 'notas canceladas do mês, destinadas baixadas, certificados vencendo em novembro'. Close nos três itens riscados.",
 "fecha outubro com tudo conferido ✅", FI, "Sem música", "G"),
("30/10","12h15","Sextou #2","Vídeo","8 s",
 "sexta, último dia útil do mês, 17h58",
 "Júlia desliga o monitor, cliente liga, ela olha o telefone tocando e olha para a câmera. Atende com voz simpática: 'oi! pode falar' (texto: 'a gente sempre atende 🥲').",
 "o compromisso fala mais alto 🥲", HU, "Som em alta CML", "G"),
("30/10","19h30","Um dia no escritório #5","Vídeo","35 s",
 "fechamento de mês num escritório contábil, sem drama",
 "Timelapse curto do dia + 3 momentos: conferência das canceladas, relatório gerado, envio aos clientes. Narração: 'o fechamento é conferência, não correria'.",
 "como é o seu último dia do mês? 👇", HU, "Lo-fi CML 10%", "G + T"),
("31/10","10h","Série · Coisas que só... (pt. 8)","Carrossel de fotos","6 fotos",
 "coisas que só quem trabalha em escritório contábil entende (edição fim de mês)",
 "1) 'zerar a caixa de entrada às 18h'; 2) 'o cliente que agradece (raridade)'; 3) 'o relatório batendo com o extrato de primeira'; 4) 'o colega que traz pão de queijo no fechamento'; 5) 'a sensação de mês fechado'; 6) 'e amanhã começa tudo de novo 🙃'.",
 "edição fim de mês, a 3 é o melhor sentimento 🥹", HU, "Som em alta CML", "D"),
("31/10","15h","Trend #3","Vídeo","8 s",
 "Halloween de contador: o que mais dá medo",
 "Júlia com tela preta, lanterna no rosto: 'certificado vencido', 'XML faltando', 'cliente sumido com o DAS'. Cada frase com um susto de áudio.",
 "qual é o seu maior medo? 👻", HU, "Som de terror cômico CML", "G"),
("31/10","20h","Bastidores do robô #6","Vídeo","10 s",
 "outubro em números (do painel de demonstração)",
 "Tela do painel de demonstração: XMLs do mês, canceladas, clientes sincronizados. Texto: 'números de demonstração, empresas fictícias'.",
 "como foi o outubro de vocês? 📊", AU, "Som eletrônico CML", "T"),
("01/11","10h","Departamento pessoal #3","Carrossel de fotos","6 fotos",
 "checklist do 13º para mandar pro cliente (salva)",
 "1) capa; 2) 1ª parcela até 30/11; 3) 2ª parcela até 20/12; 4) quem tem direito: quem trabalhou 15 dias ou mais no mês conta como mês; 5) FGTS sobre o 13º; 6) 'manda isso pro cliente hoje'.",
 "salva e manda pros clientes com funcionário 📌", DP, "Som leve CML", "D"),
("01/11","15h","Tipos de cliente #7","Vídeo","10 s",
 "tipos de cliente: o que já chega com tudo pronto num pen drive",
 "Cliente (Marcos fazendo o papel) entrega um pen drive com etiqueta 'NOTAS 2024-2026 ORGANIZADO'. Júlia abre: 1 pasta 'Nova pasta (3)'. Ela sorri.",
 "pelo menos veio num pen drive 🫡", HU, "Som em alta CML", "G"),
("01/11","20h","Domingo antes de novembro","Vídeo","7 s",
 "novembro: 13º, Black Friday dos clientes e o ano acabando",
 "Júlia olhando o calendário de novembro, respira fundo, fecha o notebook e liga a TV.",
 "força pra todos nós em novembro 💪", HU, "Som em alta CML", "G"),
("02/11","10h","Feriado de Finados","Vídeo","8 s",
 "feriado: o celular do contador também merece descanso",
 "Júlia coloca o celular em 'não perturbe', deixa na mesa e sai para caminhar. Texto: 'volto amanhã, clientes 💚'.",
 "desconecta hoje, sério 🌿", HU, "Som calmo CML", "G"),
("02/11","15h","Glossário relâmpago #5","Carrossel de fotos","5 fotos",
 "MEI, ME, EPP: os limites de faturamento em 1 minuto",
 "1) capa; 2) MEI: até R$ 81 mil/ano; 3) Simples Nacional: até R$ 4,8 milhões/ano; 4) sublimite de R$ 3,6 milhões para ICMS e ISS; 5) 'acompanhar mês a mês evita susto'.",
 "salva pra explicar pro cliente 📌", SN, "Som leve CML", "D"),
("02/11","20h","Bastidores do robô #7","Vídeo","10 s",
 "feriado de novo, robô trabalhando de novo",
 "Tela: sincronização 12:00 ✓. Texto: 'o robô não pediu folga'.",
 "🤖", AU, "Som eletrônico CML", "T"),
("03/11","07h30","Reforma em 30 segundos #8","Vídeo","35 s",
 "como explicar a reforma tributária para o cliente em 3 frases",
 "Ana: '1. Vários impostos vão virar dois: IBS e CBS. 2. A transição é longa, vai até 2033. 3. Por enquanto, muda a nota e a forma de conferir, e a gente cuida disso.'",
 "copia e manda pro cliente 😉", RF, "Lo-fi CML 5%", "G"),
("03/11","12h15","Série · Coisas que só... (pt. 9)","Vídeo","12 s",
 "coisas que só quem trabalha em escritório contábil entende (parte 9)",
 "1) A pessoa que fala 'deixa eu só ver uma coisinha' e some 40 minutos no sistema. 2) Cliente liga e pergunta pelo 'contador' e qualquer um atende. 3) O café da tarde que vira reunião.",
 "parte 9 ☕ marca quem some 40 minutos", HU, "Som em alta CML", "G"),
("03/11","19h30","Respondendo comentários #4","Vídeo","25 s",
 "respondendo: 'vocês mostram dado de cliente nos vídeos?'",
 "Ana, séria e tranquila: 'Não. Toda tela que aparece aqui é de demonstração, com empresas e CNPJs inventados. Dado de cliente é sigilo e LGPD. Se um dia aparecer cliente real, vai ser com autorização por escrito.'",
 "confiança é o que segura o cliente 🔐", AU, "Sem música", "G"),
("04/11","07h30","Departamento pessoal #4","Vídeo","25 s",
 "férias coletivas no fim do ano: o que o cliente precisa saber agora",
 "Pedro: 'Se o cliente vai dar férias coletivas em dezembro, precisa comunicar com antecedência e organizar o pagamento das férias antes do início. Pergunta hoje, não em 20 de dezembro.'",
 "pergunta pros clientes hoje 📲 (confira as regras com o seu DP)", DP, "Lo-fi CML", "G"),
("04/11","12h15","Cliente diz vs contador entende #4","Vídeo","12 s",
 "cliente diz vs contador entende (edição fim de ano)",
 "'vou fazer uma promoção na Black Friday' → 'vai faturar o dobro em um mês'; 'quero dar um bônus de Natal' → 'precisa ver como lançar'; 'vou comprar um carro pela empresa' → 'vamos conversar'.",
 "fim de ano é cheio de 'vamos conversar' 😅", HU, "Som em alta CML", "G"),
("04/11","19h30","Um dia no escritório #6","Vídeo","35 s",
 "um dia com o estagiário de DP",
 "Pedro mostra o dia: confere ponto, lança horas extras, tira dúvida com a Ana, envia eventos do eSocial, almoço. Narração simples dele.",
 "estagiário também tem vlog 😄", DP, "Lo-fi CML 10%", "G"),
("05/11","07h30","Glossário relâmpago #6","Vídeo","20 s",
 "CST do IBS/CBS: o que é, em 20 segundos",
 "Ana: 'CST é o código de situação tributária. No IBS e na CBS ele diz se a operação é tributada normal, com redução, isenta e por aí vai. Junto com o cClassTrib, ele explica a tributação do item.'",
 "salva pro dia que o cliente perguntar 📌", RF, "Lo-fi CML", "G"),
("05/11","12h15","POV #5","Vídeo","9 s",
 "POV: o cliente manda o XML certo, no formato certo, sem você pedir",
 "Júlia lê o e-mail, encosta na cadeira, olha para o teto com as mãos no peito.",
 "existe e é lindo 🥹", HU, "Som emocionante CML", "G"),
("05/11","19h30","Bastidores do robô #8","Vídeo","12 s",
 "como fica o limite do Simples de um cliente em novembro",
 "Tela do painel: barra de faturamento x limite, projeção do ano, alerta 'Atenção'. Ana explica em 2 frases.",
 "novembro é o mês de olhar o limite 👀", SN, "Lo-fi CML", "T + G"),
("06/11","07h30","Reforma em 30 segundos #9","Vídeo","30 s",
 "o que mudou em outubro com a NFS-e (1 mês depois)",
 "Ana: 'Um mês de NFS-e com IBS e CBS. O que a gente viu: cliente perguntando do PDF novo e emissor que ainda não manda o grupo completo. Confere o XML de pelo menos uma nota de cada cliente.'",
 "e aí, como foi no seu escritório? 👇", RF, "Lo-fi CML 5%", "G"),
("06/11","12h15","Tipos de cliente #8","Vídeo","10 s",
 "tipos de cliente: o que manda presente no fim do ano",
 "Entregador chega com uma cesta. Cartão: 'obrigado pelo ano, equipe! 💚'. Todos param, Júlia abraça a cesta.",
 "esse cliente vai pro céu 🎁", HU, "Som emocionante CML", "G"),
("06/11","19h30","Sextou #3","Vídeo","8 s",
 "sexta no escritório: a última hora",
 "Músicas baixinhas, Ana arruma a mesa, Pedro desliga o PC, Júlia apaga a luz. Plano geral, sem fala.",
 "bom fim de semana, contabilidade 🫶", HU, "Som em alta CML, vibe tranquila", "G"),
("07/11","10h","Série · Coisas que só... (pt. 10)","Carrossel de fotos","6 fotos",
 "coisas que só quem trabalha em escritório contábil entende (parte 10)",
 "1) 'explicar pela 5ª vez o que é pró-labore'; 2) 'o cliente que chama a gente de despachante'; 3) 'o orgulho de achar um erro antes da fiscalização'; 4) 'ser o primeiro a saber da reforma na família'; 5) 'e o último a saber da fofoca do escritório'; 6) 'parte 11? comenta a sua'.",
 "chegamos na parte 10 🎉 obrigada por cada comentário", HU, "Som em alta CML", "D"),
("07/11","15h","Ferramentas que eu indicaria #4","Vídeo","30 s",
 "3 hábitos que deixam um escritório pequeno parecer grande",
 "Ana fala para a câmera: '1. Responder o cliente no mesmo dia, mesmo que seja pra dizer quando vai resolver. 2. Mandar relatório do mês sem o cliente pedir. 3. Avisar antes: limite, certificado, prazo. Atendimento é o que o cliente vê.'",
 "qual você já faz? ✅", AU, "Lo-fi CML 5%", "G"),
("07/11","20h","Trend #4","Vídeo","8 s",
 "eu explicando pra minha mãe o que eu faço no trabalho",
 "Júlia gesticulando no sofá, mãe (atriz) acenando com a cabeça e no final: 'então você é do imposto de renda?'.",
 "toda família acha que a gente só faz IR 😂", HU, "Som trend CML", "G"),
("08/11","10h","Departamento pessoal #5","Vídeo","25 s",
 "13º: o erro mais comum no cálculo de quem foi contratado no meio do ano",
 "Pedro: 'Conta 1/12 por mês trabalhado, e só conta o mês em que a pessoa trabalhou 15 dias ou mais. Contratou dia 20? Aquele mês não entra.' Texto com exemplo simples.",
 "salva pro cálculo de novembro 📌", DP, "Lo-fi CML", "G"),
("08/11","15h","Tipos de cliente (votação)","Vídeo","12 s",
 "qual tipo de cliente é o seu favorito? (votação)",
 "Montagem rápida dos tipos já apresentados (cliente do 'oi', do dia 19, do pen drive, do presente) com número na tela. 'comenta o número'.",
 "vota aí 👇 o mais votado ganha episódio especial", HU, "Som em alta CML", "G"),
("08/11","20h","Um dia no escritório #7 (balanço)","Vídeo","30 s",
 "1 mês postando a rotina de um escritório contábil: o que eu aprendi",
 "Júlia senta e fala: 'contador se identifica com verdade, não com perfeição. Os vídeos que mais deram certo foram os mais simples. E vocês salvam tudo que é checklist.' Mostra o celular com os comentários.",
 "obrigada por esse mês 💚 o que vocês querem ver em novembro?", HU, "Lo-fi CML 10%", "G"),
]
