from tiktok_1 import HU, RF, FI, SN, DP, AU
TT = [
# ---------------- SEMANA 2 ----------------
("17/10","10h","Série · Coisas que só... (pt. 4)","Vídeo","14 s",
 "coisas que só quem trabalha em escritório contábil entende (parte 4)",
 "1) Júlia digita a senha do e-CAC errada 2x e para antes da 3ª. 2) A impressora que só é usada pra imprimir procuração e trava justamente aí. 3) Duas pessoas falando 'qual é o CNPJ mesmo?' ao mesmo tempo.",
 "parte 4 🫠 a da impressora é pessoal", HU, "Som em alta CML", "G"),
("17/10","15h","Um dia no escritório #2 (sábado)","Vídeo","20 s",
 "sim, às vezes contador trabalha no sábado (mas só às vezes)",
 "Júlia de roupa casual abre o notebook em casa, confere 2 alertas no painel pelo celular, resolve em 10 minutos, fecha e vai sair com amigos. Texto: 'sábado de 10 minutos > sábado inteiro'.",
 "a meta é essa: 10 minutos e não o sábado inteiro ⏱️", AU, "Lo-fi CML", "G + T"),
("17/10","20h","Trend #1","Vídeo","8 s",
 "me explica em 1 palavra o seu mês de outubro",
 "Júlia aponta para a câmera e muda de expressão no ritmo do som; 3 palavras aparecem: 'reforma' 'NFS-e' 'café'.",
 "escreve a sua palavra 👇", HU, "Som trend CML com 3 batidas", "G"),
("18/10","10h","Ferramentas que eu indicaria #2","Vídeo","30 s",
 "como eu organizo os prazos de 50 clientes sem planilha gigante",
 "Júlia mostra o celular e o computador: 1) agenda com alerta 3 dias antes do vencimento; 2) etiquetas no WhatsApp Business por status (aguardando doc, conferindo, ok); 3) painel com alerta de certificado vencendo. Fala natural e rápida.",
 "rotina que funciona pra escritório pequeno 📌", AU, "Lo-fi CML 5%", "G + T"),
("18/10","15h","Tipos de cliente #3","Vídeo","10 s",
 "tipos de cliente: o que pergunta 'quanto eu pago de imposto' por áudio às 22h",
 "Celular em cima do criado-mudo, tela acende às 22:14 com áudio de 2min. Júlia (deitada) olha, vira o celular para baixo. Texto: 'amanhã às 8h eu respondo, juro'.",
 "limite saudável também é contabilidade 🙂", HU, "Som em alta CML", "G"),
("18/10","20h","Véspera do dia 20","Vídeo","7 s",
 "domingo antes do dia 20 ser numa terça",
 "Júlia fazendo lista de tarefas no caderno, risca 'conferir DAS' e escreve 'segunda: conferir DAS DE NOVO'.",
 "conferir duas vezes não é exagero, é método 😅", SN, "Som em alta CML", "G"),
("19/10","07h30","Prazo da semana","Vídeo","15 s",
 "amanhã é dia 20: checklist de 3 itens",
 "Júlia apontando para a tela: '1, DAS gerado e enviado pra todos do Simples. 2, guia do FGTS Digital conferida. 3, cliente avisado por mensagem, não só por e-mail.'",
 "salva pro próximo dia 20 também 📌", SN, "Sem música", "G"),
("19/10","12h15","POV #2","Vídeo","10 s",
 "POV: dia 19 e o cliente pergunta 'o que é DAS?'",
 "Júlia lendo mensagem, pisca devagar, começa a digitar uma explicação longa, apaga, e manda só: 'te liguei, atende 😊'.",
 "explicar DAS no dia 19 é um esporte 🏃‍♀️", SN, "Som em alta CML", "G"),
("19/10","19h30","Bastidores do robô #3","Vídeo","12 s",
 "o alerta que salvou o mês do cliente",
 "Tela do painel (fictício): 'Ferragem Exemplo · Atenção · projeção passa do sublimite em novembro'. Ana aponta, liga pro cliente. Texto: 'alerta em outubro > susto em janeiro'.",
 "descobrir antes é a parte boa do trabalho 📈", SN, "Lo-fi CML", "T + G"),
("20/10","07h30","Dia 20","Vídeo","8 s",
 "hoje é dia 20, então hoje a gente só fala com o cliente se for por DAS",
 "Júlia de fone, digitando rápido, levanta o dedo indicador para a colega que se aproximou ('só um minuto'). A colega volta de ré.",
 "bom dia 20 pra quem é de bom dia 20 🫡", HU, "Som em alta CML acelerado", "G"),
("20/10","12h15","Cliente diz vs contador entende #2","Vídeo","12 s",
 "cliente diz vs contador entende (edição dia 20)",
 "'paguei ontem' → 'agendou pra hoje às 23h'; 'meu sobrinho faz as notas' → 'CFOP aleatório'; 'pode deixar que eu vejo' → 'você vai ver'.",
 "qual dessas você ouviu hoje? 😂", HU, "Som em alta CML", "G"),
("20/10","19h30","Fim do dia 20","Vídeo","9 s",
 "18h do dia 20: todos os DAS pagos",
 "Júlia e Ana batem as mãos discretamente, Júlia desliga o monitor. Câmera mostra o quadro: 'DAS ✓'.",
 "vencemos mais um dia 20 🏁", HU, "Som triunfal leve da CML", "G"),
("21/10","07h30","Reforma em 30 segundos #4","Vídeo","35 s",
 "NFS-e padrão nacional: o que muda pro escritório",
 "Ana: 'A NFS-e nacional junta o layout das prefeituras num padrão só. Pra quem baixa e confere nota de serviço, isso significa um XML parecido pra todo município e as retenções sempre no mesmo lugar.' Corte pra tela com o XML.",
 "nota de serviço finalmente com cara de padrão 🙏", RF, "Lo-fi CML 5%", "G + T"),
("21/10","12h15","Série · Coisas que só... (pt. 5)","Carrossel de fotos","6 fotos",
 "coisas que só quem trabalha em escritório contábil entende (parte 5)",
 "1) 'quando o cliente manda o XML em PDF'; 2) 'quando manda o PDF em foto'; 3) 'quando manda a foto do PDF impresso'; 4) 'a planilha de controle com 14 abas e uma chamada FINAL_v3'; 5) 'o grupo do escritório às 7h: alguém tem a senha do portal?'; 6) 'e a gente ama mesmo assim 💚'.",
 "parte 5, a 4 é universal 📊", HU, "Som em alta CML", "D"),
("21/10","19h30","Um dia no escritório #3","Vídeo","40 s",
 "como funciona uma reunião de segunda num escritório contábil",
 "Mesa pequena, 4 pessoas, notebook aberto: Marcos lê a lista de prazos da semana, cada um diz 1 travamento, Ana anota. Termina em 15 minutos. Narração curta da Júlia: 'reunião curta, todo mundo sabe o que faz'.",
 "15 minutos que poupam a semana inteira ⏱️", HU, "Lo-fi CML", "G"),
("22/10","07h30","Glossário relâmpago #3","Vídeo","20 s",
 "CFOP em 20 segundos (pro cliente parar de chutar)",
 "Júlia com post-it na mão: 'CFOP é o código da natureza da operação. Começa com 5 ou 6 na saída, 1 ou 2 na entrada. Errou o CFOP, o faturamento sai errado e o limite do Simples também.'",
 "salva e manda pro sobrinho que faz as notas 😅", FI, "Lo-fi CML", "G"),
("22/10","12h15","POV #3","Vídeo","9 s",
 "POV: você acha a nota que o cliente jurava que não existia",
 "Júlia digita o número no painel, nota aparece, ela vira o monitor para a câmera, sorriso discreto de vitória.",
 "o print vai direto pro grupo 📸", FI, "Som de vitória CML", "G + T"),
("22/10","19h30","Respondendo comentários #2","Vídeo","25 s",
 "respondendo: 'e quando a SEFAZ cai, o robô faz o quê?'",
 "Júlia mostra a tela: 'Se a SEFAZ estiver fora, o robô tenta de novo na próxima janela, ao meio-dia ou à meia-noite, e o painel mostra quando foi a última sincronização de cada cliente. Ninguém precisa ficar dando F5.'",
 "pergunta boa, manda mais 👇", AU, "Sem música", "G + T"),
("23/10","07h30","Reforma em 30 segundos #5","Vídeo","40 s",
 "3 perguntas que o seu cliente vai fazer sobre IBS/CBS (e as respostas)",
 "Ana: '1. Vou pagar mais? Em 2026, não. 2. Por que minha nota mudou? Porque agora ela mostra IBS e CBS. 3. Preciso fazer algo? Se for do Simples, a partir de janeiro: confirmar com o emissor.'",
 "copia e cola pro seu cliente 😉", RF, "Lo-fi CML 5%", "G"),
("23/10","12h15","Tipos de cliente #4","Vídeo","10 s",
 "tipos de cliente: o que some no ano todo e aparece em dezembro",
 "Calendário na parede, mão passa os meses. Em dezembro: notificação 'oi, sumida! preciso de tudo do ano 🥲'. Júlia ri incrédula.",
 "todo escritório tem um 🎄", HU, "Som em alta CML", "G"),
("23/10","19h30","Sextou no escritório","Vídeo","8 s",
 "sexta 17h59 num escritório contábil",
 "Todo mundo já com a bolsa no ombro, Marcos ainda falando 'só uma coisinha', todos param e olham pra ele. Ele: 'segunda eu falo'. Todos saem.",
 "o 'só uma coisinha' de sexta 😂", HU, "Som em alta CML", "G"),
]
