# Produção: G = gravar com a equipe no celular · S = vídeo real de banco gratuito (Pexels/Pixabay) + texto
#           T = gravação de tela do Painel · D = design/fotos (eu produzo) · I = vídeo IA (prompt pronto)
HU = "#contabilidade #contador #escritoriocontabil #vidadecontador #humorcontabil"
RF = "#reformatributaria #ibscbs #nfse #contabilidade #contador"
FI = "#fiscal #notafiscal #contabilidade #contador #escritoriocontabil"
SN = "#simplesnacional #mei #pgdas #contabilidade #contador"
DP = "#departamentopessoal #esocial #folhadepagamento #contabilidade #contador"
AU = "#automacaocontabil #escritoriocontabil #contabilidade #tecnologia #contador"
TT = [
# ---------------- SEMANA 1 ----------------
("10/10","10h","Série · Coisas que só quem trabalha em escritório contábil entende (pt. 2)","Vídeo","12 s",
 "coisas que só quem trabalha em escritório contábil entende (parte 2)",
 "1) Close no celular em cima da mesa: chega áudio de cliente de 3min47s. Júlia olha, respira fundo, põe o fone. 2) Júlia no WhatsApp Web, 3 conversas com '(1)' piscando, ela abre a de cima. 3) Colega da mesa ao lado pergunta 'é aquele cliente?', ela só confirma com a cabeça.",
 "parte 2 porque a parte 1 vocês aprovaram 😮‍💨 qual faltou?", HU, "Som em alta da CML, tom de desabafo leve", "G (ou S: 'woman office phone headphones')"),
("10/10","15h","Reforma em 30 segundos #1","Vídeo","35 s",
 "o que é cClassTrib (e por que vai aparecer em toda nota)",
 "Ana na mesa, fala direto para a câmera, monitor ao fundo: 'cClassTrib é o código de classificação tributária do item. Ele diz ao fisco como aquele produto ou serviço é tratado no IBS e na CBS.' Corte para a tela: campo cClassTrib no XML, destacado. Ana: 'Em 2026 é teste. Em 2027 o Simples entra. Quem já classifica hoje não corre em dezembro.'",
 "cClassTrib explicado sem enrolação 🧾 salva pra mostrar pro cliente", RF, "Sem música ou lo-fi a 5%", "G + T"),
("10/10","20h","Fim de semana de contador","Vídeo","8 s",
 "sábado 20h e o meu cérebro ainda lembrando de nota de entrada",
 "Júlia no sofá com amigos, rindo; para no meio da risada, olha pro nada por 2s e pega o celular. Texto: 'será que eu conferi as destinadas da Padaria?'.",
 "alguém mais? 😭", HU, "Trend com som de 'pausa dramática' da CML", "G"),
("11/10","10h","Ferramentas que eu indicaria (indicação #1)","Carrossel de fotos","6 fotos",
 "5 coisas grátis que todo escritório contábil deveria usar",
 "1) capa: Júlia segurando o celular. 2) App Receita Federal / e-CAC no celular (consultas rápidas). 3) Portal Nacional da NFS-e (emissor e consulta). 4) Agenda tributária da Receita no calendário do Google com alerta. 5) WhatsApp Business com etiquetas por cliente. 6) 'e um robô que baixa XML às 00h (esse não é grátis, mas paga o café 🤖)'.",
 "salva essa lista 📌 qual você usa e não tá aqui?", FI, "Som em alta CML, leve", "D (fotos) "),
("11/10","15h","Tipos de cliente #1","Vídeo","10 s",
 "tipos de cliente: o que manda 'oi' e some",
 "Celular na mesa: notificação 'Oi'. Júlia responde 'Oi! Tudo bem? Como posso ajudar?'. Corte: 2h depois (texto na tela), nenhuma resposta. Corte: 18h, chega 'tá aí?'. Júlia olha pra câmera, sem expressão.",
 "esse cliente existe em todo escritório 🫠 marca o colega que atende ele", HU, "Som de suspense cômico da CML", "G"),
("11/10","20h","Domingo à noite","Vídeo","7 s",
 "domingo 20h: a vibe de quem tem fechamento amanhã",
 "Júlia abrindo a agenda no notebook em casa, olha a semana (dia 20 marcado), fecha o notebook devagar e puxa o cobertor.",
 "a semana do dia 20 começa no domingo 🙂", HU, "Som em alta CML, melancólico/engraçado", "G"),
("12/10","10h","Feriado","Vídeo","8 s",
 "feriado pra todo mundo menos pro portal que eu preciso usar amanhã",
 "Júlia tomando café na varanda, relaxada. Texto: 'feriado 🎉'. Pega o celular, vê mensagem de cliente 'amanhã vc consegue ver aquilo cedinho?'. Suspira e sorri amarelo.",
 "feliz feriado pra quem conseguiu desligar 🫡", HU, "Som em alta CML", "G"),
("12/10","15h","Glossário relâmpago #1","Carrossel de fotos","5 fotos",
 "NF-e, NFC-e, NFS-e, CT-e: qual é qual (pra explicar pro estagiário)",
 "Slides de texto nativo sobre foto do escritório: NF-e = venda de mercadoria entre empresas; NFC-e = venda no varejo ao consumidor; NFS-e = serviço (agora com padrão nacional); CT-e = transporte de carga; último: 'manda pro estagiário 🫶'.",
 "manda pro estagiário que ainda confunde 😅", FI, "Som leve CML", "D"),
("12/10","20h","Bastidores do robô #1","Vídeo","12 s",
 "o que o robô fez enquanto você estava no feriado",
 "Gravação de tela (dados fictícios) do Painel: lista 'sincronizado 00:00 ✓' por cliente, contador de XMLs subindo, canceladas marcadas. Texto: 'feriado pra gente, dia normal pra SEFAZ'.",
 "a SEFAZ não tira feriado, então o robô também não 🤖", AU, "Som satisfatório/eletrônico CML", "T"),
("13/10","07h30","Reforma em 30 segundos #2","Vídeo","40 s",
 "IBS e CBS na nota: o cliente vai pagar mais imposto em 2026?",
 "Ana falando pra câmera: 'Não. Em 2026 é teste: CBS 0,9% e IBS 0,1% destacados, que podem ser compensados com PIS e Cofins. O que muda é o XML e o PDF. O cliente vai ver um número novo na nota e vai te ligar. Já deixa a resposta pronta.' Corte pro quadro IBS/CBS no DANFE.",
 "a pergunta que você vai ouvir essa semana 👇", RF, "Lo-fi CML 5%", "G + T"),
("13/10","12h15","Cliente diz vs contador entende #1","Vídeo","12 s",
 "o que o cliente diz vs o que o contador entende",
 "Tela dividida em 3 falas com Júlia reagindo: 'é rapidinho' → 'vai levar a tarde'; 'te mando amanhã' → 'te mando dia 19'; 'não mudou nada' → 'abriu filial'.",
 "traduzindo cliente desde sempre 📖 qual você acrescentaria?", HU, "Som em alta CML com batidas para cada frase", "G"),
("13/10","19h30","Um dia no escritório #1 (vlog)","Vídeo","45 s",
 "um dia normal num escritório contábil (sem filtro)",
 "08h: chega, liga os 2 monitores, abre WhatsApp Web e o sistema. 09h: confere notas do dia no painel. 10h30: café na copa com a Ana, conversa rápida. 13h: almoço. 15h: ligação de cliente sobre boleto do DAS. 17h: confere a fila de tarefas. 18h05: apaga a luz. Narração da Júlia, natural, em off.",
 "vlog sem glamour, porque escritório é assim mesmo 😄", HU, "Lo-fi CML 10% por baixo da narração", "G"),
("14/10","07h30","Prazo da semana","Vídeo","15 s",
 "dia 20 está chegando: o que vence",
 "Júlia aponta para o quadro branco de prazos do escritório: 'DAS do Simples e FGTS Digital vencem dia 20. Esse mês cai numa terça. Não deixa pra segunda à noite.' Close no quadro.",
 "anota aí 📌 (e confere a agenda tributária oficial)", SN, "Sem música", "G"),
("14/10","12h15","POV #1","Vídeo","9 s",
 "POV: o certificado digital do cliente vence hoje e ele tá viajando",
 "Júlia vê alerta 'certificado vence hoje' no painel, pega o telefone, liga. Cai na caixa postal. Ela encosta a testa na mão, sem drama.",
 "renova antes, eu imploro 🙏", FI, "Som em alta CML de tensão", "G + T"),
("14/10","19h30","Respondendo comentários #1","Vídeo","25 s",
 "respondendo: 'vale a pena automatizar escritório pequeno?'",
 "Marcos (sócio) sentado, fala tranquilo: 'Pensa num escritório de 4 pessoas com 50 clientes. O que mais come tempo é baixar e organizar nota. Automatizar isso não é coisa de escritório grande, é o que deixa o pequeno crescer sem contratar mais um só pra baixar XML.'",
 "responde aqui embaixo: quantas horas por mês vocês gastam baixando nota? 👇", AU, "Sem música", "G"),
("15/10","07h30","Glossário relâmpago #2","Vídeo","20 s",
 "nota cancelada vs nota substituída: diferença em 20 segundos",
 "Júlia com o painel aberto (tela): 'Cancelada: a nota deixa de valer, sai da soma. Substituída: no caso da NFS-e, uma nova nota substitui a anterior, e a antiga também sai do faturamento. Se você soma as duas, o faturamento do cliente dobra no papel.' Mostra tag 'Cancelada' e 'Substituída'.",
 "esse erro aparece no limite do Simples depois 👀", FI, "Lo-fi CML 5%", "G + T"),
("15/10","12h15","Série · Coisas que só... (pt. 3)","Carrossel de fotos","7 fotos",
 "coisas que só quem trabalha em escritório contábil entende (parte 3)",
 "Fotos reais/realistas: 1) 'o boleto do DAS mandado em foto torta'; 2) 'cliente: já paguei? (não pagou)'; 3) 'o sistema da prefeitura que só funciona no Internet Explorer da alma'; 4) 'senha gov.br do cliente: ninguém sabe'; 5) 'quando o cliente abre empresa e te conta depois'; 6) 'a satisfação de zerar a fila de tarefas'; 7) 'e o café que esfriou do lado do teclado'.",
 "parte 3! a 6 é a melhor sensação do mundo ✨", HU, "Som em alta CML", "D"),
("15/10","19h30","Bastidores do robô #2","Vídeo","10 s",
 "ASMR de nota fiscal se organizando sozinha",
 "Gravação de tela: XMLs entrando nas pastas cliente > mês > modelo, com som de clique e 'ding'. Sem fala.",
 "o ASMR mais contábil que você vai ver hoje 🎧", AU, "Áudio original (cliques) + som satisfatório CML", "T"),
("16/10","07h30","Reforma em 30 segundos #3","Vídeo","35 s",
 "Simples Nacional em 2027: o que muda na nota do seu cliente",
 "Ana: 'Em janeiro, empresa do Simples passa a preencher IBS e CBS na nota, ainda em teste. Quem precisa se mexer agora: quem emite por sistema próprio ou emissor antigo. Pergunta pro fornecedor do emissor se a versão com o grupo IBSCBS já tá pronta.'",
 "manda pro cliente que tem emissor próprio 📲", RF, "Sem música", "G"),
("16/10","12h15","Tipos de cliente #2","Vídeo","10 s",
 "tipos de cliente: o que manda tudo no dia 19 às 17h",
 "Relógio do computador marcando 17:02 (close). Notificação: 'segue as notas do mês 😊' com 1 anexo .zip de 300 MB. Júlia apenas vira a cadeira para a colega. A colega: 'de novo?'.",
 "o 'segue as notas' mais temido do Brasil 🫠", HU, "Som em alta CML", "G"),
("16/10","19h30","Opinião / debate #1","Vídeo","20 s",
 "contador deveria cobrar à parte pelo trabalho da reforma tributária?",
 "Marcos de pé na sala de reunião: 'Minha opinião: a transição é trabalho extra, classificar item, conferir XML, orientar. Eu prefiro combinar um valor claro com o cliente do que absorver calado.' Texto: 'concorda?'.",
 "sim ou não? defende sua opinião nos comentários 👇", RF, "Sem música", "G"),
]
